# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-13 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lets_play_app.Reservation'),
        ),
    ]
