# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-01 15:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0002_auto_20180301_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='user1',
            new_name='user_main',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user2',
            new_name='user_partner',
        ),
    ]
