# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-16 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0002_auto_20180313_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='ranking',
            field=models.IntegerField(default=0),
        ),
    ]
