# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 21:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0002_auto_20180305_2102'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Score',
        ),
    ]
