# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-25 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0003_auto_20180316_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
