# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-05 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0003_auto_20180305_2102'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
