# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 11:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0004_auto_20180301_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='skill',
            field=models.IntegerField(choices=[(1, 'Szturmowiec'), (2, 'Padawan'), (3, 'Rycerz Jedi'), (4, 'Mistrz Joda')], null=True),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.IntegerField(choices=[(10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00')], verbose_name='Koniec rezerwacji'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_start',
            field=models.IntegerField(choices=[(1, '10:00'), (2, '11:00'), (3, '12:00')], verbose_name='Początek rezerwacji'),
        ),
    ]
