# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-02 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0005_auto_20180302_1105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time_end',
            field=models.TimeField(verbose_name='Koniec rezerwacji'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='time_start',
            field=models.TimeField(verbose_name='Początek rezerwacji'),
        ),
    ]
