# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-03-09 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lets_play_app', '0006_auto_20180309_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstats',
            name='games_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='games_won',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='sets_lost',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userstats',
            name='sets_won',
            field=models.IntegerField(default=0),
        ),
    ]
